---
title: "Untitled"
author: "Kaushik Mohan"
date: "12/11/2018"
output: html_document
---

```{r setup, include=FALSE}
load(file="../data/pre_cleaning_sales_data.RData")
```


```{r}
commercial_condos <- c("RA","RB","RG","RH","RK","RP","RS","RP","RW","R5")
sales_data_w_assessment <- sales_data_w_assessment[!(sales_data_w_assessment$building_class_at_time_of_sale %in% commercial_condos),]

sales_data_w_assessment <- sales_data_w_assessment %>% filter(sale_price > 10000)
```


```{r}
condos <- sales_data_w_assessment[sales_data_w_assessment$building_class == "R",]
coops <- sales_data[sales_data$building_class == "D",]

sales_data <- sales_data_w_assessment[sales_data_w_assessment$building_class %in% c("A","B","C","S"),]

```

```{r}
plot(coops$gross_square_feet,coops$GR.SQFT)
```

```{r}
condos$ResArea <- as.numeric(condos$ResArea)
condos$gross_square_feet <- as.numeric(condos$gross_square_feet)
condos$area <- NA

condos$area[condos$GR.SQFT > 0] <- condos$GR.SQFT[condos$GR.SQFT > 0]
condos$area[condos$ResArea > 0] <- condos$ResArea[condos$ResArea > 0]

condos$price_per_sq_ft <- condos$sale_price/condos$area
condos$price_per_sq_ft[is.na(condos$price_per_sq_ft)] <- 0
```


```{r}
plot(density(log10(condos$price_per_sq_ft[condos$price_per_sq_ft > 0])))
```

```{r}
assessment_data[(assessment_data$BORO == 1 & assessment_data$BLOCK == 15 & assessment_data$LOT == 1230),]

535000/523
```

